version: '3'

services:
  app:
    image: node:12
    command: sh -c "yarn && yarn start"
    ports:
      - 8081:8081
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env.app
    stdin_open: true
    tty: true
